export const gamesSeed = [
  {
    id: "omerta",
    slug: "omerta",
    title: "Omertà",
    name: "Omertà",
    status: "available",
    eyebrow: "Juegos que tocan mesa",
    tagline: "¿Callar o Traicionar? La decisión es tuya",
    cardLine: "Callar o traicionar, la decisión es tuya.",
    summary: "El silencio es una estrategia. Un juego social de confianza, traición y todo lo que se calla.",
    desc: [
      "Un juego social de confianza, traición y todo lo que se calla. Cada jugador guarda un secreto y una agenda; nadie sabe del todo de qué lado está el de enfrente.",
      "Las reglas son simples. Las decisiones no. Hablar te delata, callar te aísla, y la mesa se inclina hacia delante esperando a que alguien parpadee primero.",
    ],
    techLabel: "Ficha técnica",
    meta: [
      { k: "Jugadores", v: "1 – 25" },
      { k: "Duración", v: "15 min" },
      { k: "Tipo", v: "Juego social" },
      { k: "Estado", v: "Disponible" },
    ],
    cta: "Descubre Omertà",
    playersMin: 1,
    playersMax: 25,
    durationMinutes: 15,
    type: "Juego social",
    tags: ["social", "deduccion", "traicion"],
    sourceUrl: "https://pixeldice.studio/es/",
    featured: true,
    updatedAt: "2026-06-15T00:00:00Z",
  },
];
